-- Adminer 4.7.5 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

SET NAMES utf8mb4;

DROP TABLE IF EXISTS `measures`;
CREATE TABLE `measures` (
  `id` int NOT NULL AUTO_INCREMENT,
  `slug` varchar(50) DEFAULT NULL,
  `pillar_id` int DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` text,
  `img` varchar(255) DEFAULT NULL,
  `target` enum('scuola','azienda') DEFAULT NULL,
  `type` int DEFAULT NULL,
  `service_url` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `measures` (`id`, `slug`, `pillar_id`, `name`, `description`, `img`, `target`, `type`, `service_url`) VALUES
(1,	'smart-working',	1,	'Smart working',	'Facilitare e consentire lo smart working, cioè dare la possibilità ai dipendenti di svolgere           le attività di lavoro lontano dalla sede lavorativa, es. casa.',	'measures/smart-working.jpg',	'azienda',	1,	''),
(2,	'riunioni-remoto',	1,	'Riunioni da remoto',	'I dipendenti possono effettuare riunioni da remoto con clienti oppure colleghi di sedi remote           grazie a strumenti che permettono le chiamate in conferenza, condivisione di schermo, ecc.',	'measures/riunioni-remoto.jpg',	'azienda',	1,	''),
(3,	'spesa-domicilio',	2,	'Spesa a domicilio o in azienda',	'Il dipendente riceve la spesa a domicilio o in azienda, senza costi aggiuntivi. Il dipendente            può evitare di venire al lavoro in auto, perchè può portare ogni giorno una piccola quantità di spesa in            bici o in autobus.',	'measures/spesa.jpeg',	'azienda',	1,	''),
(4,	'farmacia',	2,	'Farmacia in azienda',	'Il dipendente riceve i prodotti di farmacia, es. parafarmaci, integratori, ecc., in azienda,           senza costi aggiuntivi. Il servizio non prevede l\'ordine e consegna di prodotti con obbligo di prescrizione           medica secondo quanto previsto dalla normativa.',	'measures/farmacia.jpg',	'azienda',	1,	''),
(5,	'lavanderia-azienda',	2,	'Lavanderia a domicilio o in azienda',	'Il dipendente consegna e riceve gli indumenti a domicilio o in azienda, senza costi aggiuntivi.',	'measures/tintoria.jpg',	'azienda',	1,	''),
(6,	'asilo-aziendale',	2,	'Asilo aziendale',	'Il dipendente ha a disposizione presso la sede lavorativa uno spazio sicuro, vicino e           comodo dove poter lasciare i bambini tra i 3 e i 36 mesi durante l’orario di lavoro. Il dipendente           può evitare di venire al lavoro in auto, perchè non deve deviare durante il suo tragitto casa-lavoro per           portare il suo bambino.',	'measures/asilo-nido.jpg',	'azienda',	1,	''),
(7,	'posteggi-bici',	3,	'Posteggi per biciclette',	'Il dipendente che si sposta in bici non si preoccupa della sua bici mentre in ufficio           perché l\'azienda offre dei posteggi sicuri e comodi.',	'measures/posteggi-bici.jpg',	'azienda',	1,	''),
(8,	'spogliatoi',	3,	'Spogliatoi',	'Il dipendente che vuole spostarsi a piedi o in bici non si preoccupa della possibilità di sudare             durante il tragitto casa-lavoro perché presso la sede lavorativa sono disponibili degli             spogliatoi dove ci si può cambiare comodamente.',	'measures/spogliatoio.jpg',	'azienda',	1,	''),
(9,	'segnaletica',	3,	'Segnaletica',	'Tutte le infrastrutture per i ciclisti presso la sede (es. posteggi, spogliatoi) sono           segnalate in modo chiaro, evidente ed accattivante.',	'measures/segnaletica-bici.jpg',	'azienda',	1,	''),
(10,	'accessibilita',	3,	'Accessibilità dell\'azienda per pedoni e bici',	'L\'azienda si assicura che sia accessibile per pedoni e ciclisti, valutando lo stato di           infrastrutture per loro intorno alla sede e dialoghando con gli enti pubblici di competenza per           risolvere eventuali problemi.',	'measures/accessibilita.jpg',	'azienda',	1,	''),
(11,	'incentivi-economici',	4,	'Incentivi economici per pedoni e ciclisti',	'L\'azienda promuove gli spostamenti casa-lavoro a piedi e in bici offrendo incentivi economici,           perché riconosce i numerosi vantaggi sia per essa sia per i dipendenti. Gli incentivi possono avere diverse          forme, es. rimborso km in denaro, raccolta punti, ecc.',	'measures/incentivi-economici.jpg',	'azienda',	1,	''),
(12,	'informazione-bici-piedi',	4,	'Attività di informazione',	'Il dipendente riceve comunicazioni e materiale informativo (es. mappe della rete ciclabile)           che mette in evidenza l\'accessibilità dell\'azienda a piedi e in bici, vantaggi e incentivi, infrastrutture           disponibili, ecc.',	'measures/informazioni.jpg',	'azienda',	1,	''),
(13,	'bike-sharing',	4,	'Servizi di bike sharing',	'Anche il dipendente che non possiede una bici oppure non gli è possibile effettuare l\'intero           spostamento casa-lavoro in bici è facilitato e incoraggiato a utilizzare questa modalità di trasporto grazie           al bike sharing. L\'azienda concorda con servizi di bike sharing esistenti offerte particolari per i suoi dipendenti.',	'measures/bike-sharing.jpg',	'azienda',	1,	''),
(14,	'bici-aziendali',	4,	'Bici aziendali',	'Il dipendente può avere in comodato d’uso bici aziendali (tradizionali oppure elettriche)           che può utilizzare per lo spostamento casa-lavoro. Le bici aziendali possono essere utilizzate anche per           gli spostamenti all’interno della sede.',	'measures/bici-aziendali.jpg',	'azienda',	1,	''),
(15,	'promozione-bici-piedi',	4,	'Promozione degli spostamenti a piedi e in bici',	'L\'azienda promuove gli spostamenti a piedi e in bici partecipando ad iniziative locali e nazionali           (es. bike to work) ma anche organizzando eventi aziendali.',	'measures/promozione-bici.jpg',	'azienda',	1,	''),
(16,	'tpl-servizio',	5,	'Trasporto pubblico conveniente e sicuro',	'L’azienda si assicura che il servizio del trasporto pubblico presente intorno alla sede corrisponde           alle esigenze dei suoi dipendenti (es. orari, frequenza, sicurezza) e collabora con gli enti pubblici e gli           operatori del trasporto pubblico per riportare eventuali migliorie.',	'measures/rete-tpl.jpg',	'azienda',	1,	''),
(17,	'navetta',	5,	'Navetta aziendale',	'L\'azienda organizza un servizio di navetta che offre un collegamento comodo e veloce per i suoi           dipendenti tra nodi importanti di trasporto pubblico (es. stazione ferroviaria, stazione della metropolitana)           e la sede lavorativa, dove non disponibile.',	'measures/navetta.jpg',	'azienda',	1,	''),
(18,	'informazione-tpl',	5,	'Attività di informazione',	'Il dipendente può accedere facilmente a tutte le informazioni utili (es. linee, orari, fermate)           per pianificare il suo spostamento casa-lavoro con il trasporto pubblico.',	'measures/informazioni.jpg',	'azienda',	1,	''),
(19,	'incentivo-abbonamento',	6,	'Incentivo per l’acquisto di abbonamenti annuali',	'Il dipendente gode di uno sconto per l’acquisto dell’abbonamento annuale per il trasporto pubblico,           grazie all’incentivo aziendale.',	'measures/tessera-abbonamento.jpg',	'azienda',	1,	''),
(20,	'promozione-tpl',	6,	'Promozione del trasporto pubblico',	'L’azienda realizza attività di comunicazione per incoraggiare l’utilizzo del trasporto pubblico e azioni             che permettono ai dipendenti di provarlo, es. offerta di biglietti/abbonamenti, comunicazione per             mostrare i costi del trasporto pubblico vs auto privata, per sfatare i falsi miti (sicurezza, bassa qualità             di servizio), ecc.',	'measures/tpl.jpg',	'azienda',	1,	''),
(21,	'carpooling',	7,	'Facilitare il carpooling',	'I dipendenti possono facilmente organizzarci in equipaggi di carpooling grazie agli strumenti messi           a disposizione dall\'azienda.',	'measures/carpooling.jpg',	'azienda',	1,	''),
(22,	'carpooling-incentivi',	7,	'Incentivi per chi fa carpooling',	'L\'azienda incoraggia il carpooling offrendo incentivi economici e non, es. rimborso km, posteggi           dedicati, ecc.',	'measures/posteggio-carpooling.jpg',	'azienda',	1,	''),
(23,	'policy-multimodalita',	8,	'Policy aziendale per la sostituzione dell\'auto con mezzi alternativi',	'L\'azienda diminuisce l\'uso dell\'auto per gli spostamenti per lavoro adottando policy che           promuovono l\'utilizzo di mezzi alternativi e la multimodalità (es. treno + car sharing).',	'measures/multimodalita.jpg',	'azienda',	1,	''),
(24,	'meno-trasferte',	8,	'Ridurre la necessità di trasferte',	'I dipendenti possono effettuare riunioni da remoto con clienti oppure colleghi di sedi remote           grazie a strumenti che permettono le chiamate in conferenza, condivisione di schermo, ecc.',	'measures/riunioni-remoto.jpg',	'azienda',	1,	''),
(25,	'posteggi-auto',	9,	'Pianificazione della sosta',	'L\'utilizzo dei posteggi auto disponibili presso la sede viene pianificata, adottando meccanismi           equi e trasparenti, in modo che disincentiva l’utilizzo dell’auto e incentiva l’uso dei mezzi alternativi.',	'measures/posteggi-auto.jpg',	'azienda',	1,	'/services/parking'),
(26,	'parco-veicolare',	10,	'Sostituzione del parco veicolare',	'Valutare la sostituzione del parco veicolare con un sistema di mobilità condivisa a più alta           efficienza (es. sistema ibrido/elettrico/car sharing).',	'measures/parco-veicolare.jpg',	'azienda',	1,	''),
(27,	'auto-elettiche',	10,	'Auto di servizio elettriche',	'Installare in azienda alcune colonnine di ricarica per l\'auto elettrica e trasformare alcuni dei mezzi in flotta             (auto di pool, auto per gli spostamenti di servizio) in auto elettriche. Queste auto possono essere brandizzate             con il logo aziendale. Si raccomanda di avere a disposizione un fornitore di energia verde ed una applicazione             per il monitoraggio dei consumi e degli utilizzi.             <br>Le auto possono essere prese a noleggio dal proprio operatore NLT a tariffe confrontabili con quelle regolari.',	'measures/auto-elettrica.jpg',	'azienda',	1,	''),
(28,	'bikesquare',	4,	'Gestione flotta bici e gps',	'Il sistema di gestione BikeSquare permette di tenere sempre sotto controllo la flotta di bici aziendali:             dalle richieste da parte dei dipendenti, all’assegnazione delle bici e il loro utilizzo (es. km percorsi).',	'servizi/BikeSquare_Logo_b2c.svg',	'azienda',	2,	'https://b2b.bikesquare.eu/servizi/company-bike-sharing'),
(29,	'pin-bike',	4,	'Gestione del rimborso km',	'Pin Bike offre una tecnologia hardware che permette la facile e corretta gestione del rimborso km per chi             utilizza la bici per gli spostamenti casa-lavoro.',	'servizi/pin-bike.jpg',	'azienda',	2,	''),
(30,	'mobike',	4,	'Bike sharing',	'In base alle esigenze dell’azienda, si può stipulare una convenzione con il servizio bike sharing             free float Mobike.',	'servizi/mobike_logo.jpg',	'azienda',	2,	''),
(31,	'carrefour',	2,	'Servizio di spesa a domicilio/azienda',	'Carrefour propone soluzioni di consegna sia a domicilio sia in azienda.',	'servizi/carrefour-logo.jpg',	'azienda',	2,	''),
(32,	'luman',	2,	'Servizio di lavanderia',	'Il servizio di lavanderia in azienda o a domicilio può essere offerto tramite L’Uman, la lavanderia online che             offre servizi di lavanderia, sartoria e calzoleria.',	'servizi/luman-logo.jpg',	'azienda',	2,	''),
(33,	'cinque',	7,	'Car sharing',	'Una convenzione con il  car sharing CinQue può permettere di diminuire la flotta aziendale e ridurre i relativi costi.',	'servizi/cinque-logo.jpg',	'azienda',	2,	'https://www.carsharingcinque.it/'),
(34,	'strumenti-manutenzione',	4,	'Strumenti per la manutenzione delle bici',	'L\'azienda dispone spazi e strumenti per la manutenzione delle bici (es. pompe d\'aria).',	'measures/manutenzione-bici.jpg',	'azienda',	1,	''),
(35,	'pedibus',	4,	'PediBus',	'Organizzare e promuovere il PediBus per lo spostamento casa-scuola. Con il PediBus i bambini vanno e tronano dalla scuola             insieme, camminando lungo un percorso prestabilito e accompagnati da adulti volontari (es. genitori, nonni, insegnanti).',	'measures/pedibus.jpg',	'scuola',	1,	''),
(36,	'carpooling-taxi',	7,	'Ritorno a casa garantito',	'I dipendenti che fanno carpooling possono utilizzare gratuitamente il taxi oppure il car sharing             (per un numero/budget limitato a mese) per tornare a casa in caso di emergenza (es. straordinario non previsto,             emergenza di salute, ecc.).',	'measures/taxi.jpg',	'azienda',	1,	''),
(37,	'cortili-senza-auto',	9,	'Cortili senza auto',	'Limitare oppure vietare totalmente la sosta di auto presso il cortile della scuola per dare spazio ai bambini, e disincentivare             gli spostamenti in auto per gli insegnanti.',	'measures/cortili-car-free.jpg',	'scuola',	1,	''),
(38,	'carpooling-scolastico',	7,	'Carpooling scolastico',	'Quando la scuola è distante dalla casa e non si può spostare in bici o con i mezzi pubblici, si può promuovere la condivisione             dell’auto per lo spostamento casa-scuola. Si può favorire l’organizzazione autonoma delle famiglie in equipaggi di carpooling             predisponendo una bacheca all’ingresso della scuola dove insegnanti e genitori possono offrire o cercare un passaggio.',	'measures/carpooling-scolastico.jpg',	'scuola',	1,	''),
(39,	'rastrelliere-scuola',	3,	'Rastrelliere dentro in cortile',	'Nel cortile della scuola sono presenti rastrelliere che permettono di posteggiare le bici in sicurezza.',	'measures/rastrelliere.jpg',	'scuola',	1,	''),
(40,	'settimana-mobilità',	4,	'Settimana della mobilità sostenibile',	'Realizzare almeno una volta all’anno la settimana di mobilità sostenibile. L’evento potrebbe includere attività             in aula e fuori, con lo scopo di promuovere gli spostamenti con mezzi sostenibili. Durante l\'intera settimana si             invita gli studenti a venire a scuola con i mezzi pubblici, in bici o a piedi. L’evento potrebbe essere realizzato             in concomitanza con la Settimana Europea della Mobilità.',	'measures/bimbo-cammina.jpg',	'scuola',	1,	''),
(41,	'mobility-team',	4,	'Mobility Team',	'Creare il Mobility Team della scuola, costituito dal Mobility Manager Scolastico, l\'amministrazione della scuola e alcuni             insegnanti. Lo scopo del Team è l\'individuazione delle azioni e dei progetti orientati ad una mobilità casa-scuola sostenibile             e sicura e la loro migliore attuazione. Il Mobility Managemer Scolastico ha il ruolo centrale nella pianificazione e realizzazione             delle azioni e in questa attività viene assistito dal Mobility Team.',	'measures/mobility-team.jpg',	'scuola',	1,	''),
(42,	'formazione',	4,	'Formazione nelle aule',	'Realizzare attività in aula che permettono di analizzare e approfondire il tema della mobilità sostenibile, es. ragionare sui             problemi causati dalla mobilità, perché la mobilità sostenibile sia la soluzione, come si spostano gli studenti e perché,             come potrbbero migliorare il loro comportamento ecc.',	'measures/formazione.jpg',	'scuola',	1,	''),
(43,	'percorsi-sicuri',	4,	'Percorsi casa-scuola sicuri',	'In base alla residenza degli studenti, individuare dei percorsi sicuri per lo spostamento casa-scuola che gli studenti             potrebbero fare a piedi o in bici. Se necessario collaborare con gli enti locali per la realizzazione di misure di             moderazione di traffico, es. zone 30, Zone Residenziali a Traffico Moderato.',	'measures/percorsi-sicuri.jpg',	'scuola',	1,	''),
(44,	'nuovi-studenti',	4,	'Settimana di benvenuto per i nuovi studenti',	'Settimana di benvenuto per i nuovi studenti durante la quale ricevono informazioni sulle loro opzioni per spostarsi             con modalità sostenibili per raggiungere la scuola. ',	'measures/nuovi-studenti.jpg',	'scuola',	1,	''),
(45,	'strade-scolastiche',	4,	'Strade scolastiche',	'Collaborare con gli enti locali per l\'implementazione di misure di moderazione del traffico sulla strada davanti alla scuola,             es. divieto di accesso delle auto all\'orario di entrata e uscita dalla scuola, zona 30, ecc.',	'measures/car-free-street.jpg',	'scuola',	1,	''),
(46,	'corsi-bici',	4,	'Corsi sulla ciclabilità e sicurezza stradale',	'In collaborazione con enti e associazioni locali, es. polizia stradale, associazioni ciclistiche, realizzare corsi             di sicurezza stradale e mobilità ciclabile, es. muoversi in sicurezza, andare in bici, manutenzione di bici, ecc.',	'measures/corsi-bici.jpg',	'scuola',	1,	''),
(47,	'influencer',	4,	'Team di influencer per la mobilità sostenibile',	'Creare un team di studenti che sviluppa e carica materiale sui social media, es. Instragram, YouTube, Facebook,             per la promozione della mobilità sostenibile e anche delle relative azioni scolastiche.',	'measures/influencer.jpg',	'scuola',	1,	''),
(48,	'bicibus',	4,	'BiciBus',	'Organizzare e promuovere il BiciBus per lo spostamento casa-scuola. Gli studenti si spostano in gruppo verso e da scuola in             bicicletta accompagnati da adulti volontari (es. genitori, nonni, insegnanti), lungo percorsi prestabiliti, messi in sicurezza,             e segnalati per essere facilmente individuabili da bambini e automobilisti.',	'measures/bicibus.jpg',	'scuola',	1,	''),
(49,	'car-pooling-hub',	7,	'Car Pooling Hub',	'Il trivago del car pooling: permette di cercare un passaggio tra varie piattaforme di car pooling con una sola ricerca.',	'measures/carpooling_logo.png',	'azienda',	1,	'http://www.sistemapiemonte.it/carpool/app/webroot/index.php/ita/journeys/search'),
(51,	'coworking',	1,	'Condividere Spazi (Coworking)',	'Offrire una sala riunioni ad altri lavoratori della rete, oppure permettere ai propri lavoratori di operare da una sede vicino a casa propria. Meno stress, meno km percorsi, meno inquinamento.',	'measures/yolk-coworking-krakow-ceKFL76RBcA-unsplash.jpg',	'azienda',	2,	'/services/coworking');

-- 2021-01-17 17:42:47
